### Menambahkan gambar baru
POST http://localhost:3000/images
Content-Type: multipart/form-data

file=@/path/to/your/image.jpg
judul=Judul gambar
deskripsi=Deskripsi gambar

### Melihat daftar gambar
GET http://localhost:3000/images

### Menghapus gambar berdasarkan ID
POST http://localhost:3000/images/delete/1
Content-Type: application/json

{}

