name : install railway

on: 
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    -  name: Checkout code
       uses: actions/checkout@v4

    -  name: Install NodeJS 18.x
       uses: actions/setup-node@v3
       with:
        node-version: 18.x

    -  name: Install Package
       run: npm install

    -  name: Install Railway Cli
       run: npm i -g @railway/cli
    
    -  name: Install Prisma
       run: npm i prisma

    -  name: Run Migration
       run: 
        export DATABASE_URL= "${{ secret.DATABASE_URL }}"
        npx prisma migrate deploy
  

    - name: Run Migration
      run: railway run --service ${{ secrets.RAILWAY_SERVICE_ID }} npx prisma migrate deploy
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}

    - name: Deplov to Railway
      run: railway run --service ${{ secrets.RAILWAY_SERVICE_ID }}
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}

